language_codes = {
    "Bulgarian": "bg",
    "Catalan": "ca",
    "Chinese (Mandarin, Simplified)": "zh", # "zh-CN", "zh-Hans",
    "Chinese (Mandarin, Traditional)": "zh-TW", # "zh-Hant",
    "Chinese (Cantonese, Traditional)": "zh-HK",
    "Czech": "cs",
    "Danish": "da",
    "Danish (Denmark)": "da-DK",
    "Dutch": "nl",
    "English": "en",
    "English (US)": "en-US",
    "English (Australia)": "en-AU",
    "English (UK)": "en-GB",
    "English (New Zealand)": "en-NZ",
    "en-IN": "en-IN",
    "Estonian": "et",
    "Finnish": "fi",
    "Flemish": "nl-BE",
    "French": "fr", 
    "French (Canada)": "fr-CA",
    "German": "de",
    "German (Switzerland)": "de-CH",
    "Greek": "el",
    "Hindi": "hi",
    "Hungarian": "hu",
    "Indonesian": "id",
    "Italian": "it",
    "Japanese": "ja",
    "Korean": "ko",
    "Korean (South Korea)": "ko-KR",
    "Latvian": "lv",
    "Lithuanian": "lt",
    "Malay": "ms",
    "Norwegian": "no",
    "Polish": "pl",
    "Portuguese": "pt",
    "Portuguese (Brazil)": "pt-BR",
    "Portuguese (Portugal)": "pt-PT",
    "Romanian": "ro",
    "Russian": "ru",
    "Slovak": "sk",
    "Spanish": "es",
    "Spanish (Latin America)": "es-419",
    "Swedish": "sv",
    "Swedish (Sweden)": "sv-SE",
    "Thai": "th",
    "Thai (Thailand)": "th-TH",
    "Turkish": "tr",
    "Ukrainian": "uk",
    "Vietnamese": "vi"

    # "Arabic": "ar",
    # "Bulgarian": "bg",
    # "Catalan": "ca",
    # "Chinese (Mandarin, Simplified)": "zh",
    # "Chinese (Mandarin, Traditional)": "zh-TW",
    # "Chinese (Cantonese, Traditional)": "zh-HK",
    # "Czech": "cs",
    # "Danish": "da",
    # "Dutch": "nl",
    # "English": "en",
    # "Estonian": "et",
    # "Finnish": "fi",
    # "Flemish": "nl-BE",
    # "French": "fr",
    # "German": "de",
    # "German (Switzerland)": "de-CH",
    # "Greek": "el",
    # "Hindi": "hi",
    # "Hungarian": "hu",
    # "Indonesian": "id",
    # "Italian": "it",
    # "Japanese": "ja",
    # "Korean": "ko",
    # "Latvian": "lv",
    # "Lithuanian": "lt",
    # "Malay": "ms",
    # "Norwegian": "no",
    # "Polish": "pl",
    # "Portuguese": "pt",
    # "Romanian": "ro",
    # "Russian": "ru",
    # "Slovak": "sk",
    # "Spanish": "es",
    # "Swedish": "sv",
    # "Thai": "th",
    # "Turkish": "tr",
    # "Ukrainian": "uk",
    # "Urdu": "ur",
    # "Urdu (Roman)": "ur-R",
    # "Vietnamese": "vi"
}

